github/auto-check-element

- package-lock.json
- src/index.js
Avoids async syntax in browsers without support.
> Replace async/await with then/catch

- src/index.js
- test/test.js
This patch moves the triggering of the `autocheck:send` event so that it happens before we check the request cache for the current request. This gives application code a opportunity to listen to this event and mutating the body before the cache check is made. Mutating the request body is helpful when application code would like, for example, add a pre- or postfix to the request body.
Example of application code listening for the send event.
```js
on('autocheck:send', '.js-check-name', function(event) {
event.detail.body.append('additionalData', 'foobar')
})
```
> make sure we trigger the send event before caching requests

- src/index.js
Return before dispatching `autocheck:send` event if we have the value already in cache.
Previously we dispatched the send event before checking if the value was in the cache causing issues where we get stuck in a "checking" state.
> dispatch send event before early return

- README.md
- src/index.js
- test/test.js
Matches the error event behavior so both error and success contain an optional message payload. The application can decide to treat the message as a warning or informational as needed.
> Rename success payload warning to message

- examples/index.html
- src/index.js
- test/karma.config.js
- test/test.js
Accept JSON as a response as well as plain text for simple checks.
When sending JSON the `text` field is required so that we can set the validity of the element but then the application can send any data as a response. The returned response will be returned via the success or error events.
This means that we'll always set the custom validity with the correct message without HTML but preserve the ability to set HTML notes on error in the application using the element.
Also updated karma.
Ref: #17
> JSON and plain text support

- src/index.js
- test/test.js
Add the `Content-Type` header to the `auto-check-error` event payload so that the application can decide what to do based on the type of response it received from the server.
Closes #23
> Set content type in error event payload

- src/index.js
- test/test.js
Me and @dgraham worked on this but ran out of time and I filled in the rest by my own. I'd be interested in hearing what you think about those changes I did to be able to raise this PR.
This PR does a few things:
- We don't dispatch error events when the error is a `AbortError` since we were the ones that aborted it and we have started a new request.
- Breaking change: We add the whole `Response` in the success event payload instead of just the response body and the content type. The application can operate however they want on the whole Response.
- Refactor so that the network events (`load`, `loadstart`, `loaden` and `error`) are dispatched at correct places.
- Refactor so that we can remove `ErrorWithResponse`.
Closes: #30
Closes: #31
> Use AbortController to cancel old requests

- src/index.js
This is the [default value](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials), but older fetch implementations use the previous default of `omit`.
> Specify same-origin credentials

- src/index.js
- test/test.js
Property setters must be implemented in terms of attribute callbacks so that both markup attributes and scripted property accessors change the element's state.
> Respond to required attribute changes

- README.md
- src/index.js
- test/test.js
Before this change we would make the element invalid while a request was being made. This was happening inside the debounced function. Which means that in the 300ms from triggering a input event a user could submit a form with the input as being valid even though it hadn't been validated yet.
This change moves the functionality that makes the input invalid while loading outside the debounced function so that this isn't possible anymore.
Ref: https://github.com/github/github/issues/125112
> Set input as invalid on input before debounce

- src/index.js
- test/test.js
Reference: https://github.com/github/github/issues/130764
This is so that we can prevent a redundant check being trigger when people blur out of an input. The `input` event fires on paste/compsitionend and just any input value changes; as far as I can see this should be enough. 
The redundant change event was caused by https://github.com/github/auto-check-element/commit/6d6a9ef830d26a04e8f5d64064df9f1a1a73586c, and I wish we can keep that change.
Notes:
- we should do some manual testing to ensure `input` event fires reliably across browsers
- if apps using `auto-check` are firing `change` event to trigger a check, they'd need to be changed to `input` instead
> Remove change event listeners

- src/index.js.flow
😭 
This causes apps importing trying to import the element to fail with a flow untyped module exception.
> missing @ in flow declaration

- README.md
- src/index.js
- test/test.js
Support for supplying CSRF token in a child element of auto-check.
Ref: https://github.com/github/github/pull/132488
> Support for CSRF token in a child element

- src/index.js
This line was previously
https://github.com/github/auto-check-element/blob/cbc4aed6297a105961c0b3cd2aef8def59dccf2d/src/index.js#L171
but got changed to 
https://github.com/github/auto-check-element/blob/1dea6c1a352d66f5768135b9ffbe931a2992f0c0/src/index.js#L197
We should consider all 200s successful.
https://developer.mozilla.org/en-US/docs/Web/API/Response/ok
> Consider all 2xx responsed successful

- README.md
This PR updates a link in README.md
The "webcomponents/custom-elements" polyfill has moved from its own repo to "webcomponents/polyfills"
> Update reference to custom elements polyfill

- CODEOWNERS
This changes the AOR for this repository from @github/web-systems-reviewers to @github/primer-reviewers 
FR will need to add @github/primer-reviewers as admin on this repository (and remove @github/web-systems-reviewers).
Refs https://github.com/github/web-systems/issues/940
>  move AOR to primer

- examples/index.html
- src/auto-check-element.ts
Fixes https://github.com/github/accessibility-audits/issues/4816
> Show form submission success messages

- README.md
- custom-elements.json
- src/auto-check-element.ts
- test/auto-check.js
- web-test-runner.config.js
This change proposed supporting the use of alternative HTTP methods.
For example, now a user can define `http-method=GET` and then component will issue a `GET` request using encoded query params instead. All values other than POST will use this new approach. The default remains POST.
> Support alternative HTTP methods

- README.md
- custom-elements.json
- examples/index.html
- package-lock.json
- src/auto-check-element.ts
- test/auto-check.js
Us folks working on improving the GitHub.com signup flow are looking to address a UX/a11y concern with the `auto-check` element: it validates on _every_ keystroke.
- This UX is frustrating to users who may not have provided a _complete_ input yet, such as a partial email address in our case. 
- This UX is frustrating to screen reader users who are spammed with announcements on every keystroke.
We should modify the behavior to align with https://primer.style/ui-patterns/forms/overview#inline-validation, which states:
> Don't attempt to validate an input before the user is done with it. Validation may be performed as the user is typing or making their selection, but only after the first time the input has been validated and the input is in an invalid state. This gives the user early …
> Align behavior with Primer guidance behind only-validate-on-blur toggle

- src/auto-check-element.ts
- test/auto-check.js
In testing https://github.com/github/auto-check-element/pull/76 in GitHub.com, we discovered cases where input would be re-validated on blur even if the input had not changed. This PR updates our valid and invalid code paths to only validate on blur if the input has not otherwise been already validated.
(for Hubbers) See internal issue: https://github.com/github/new-user-experience/issues/242, task #1.
> do not re-validate on blur if already validated

- examples/index.html
In a previous PR, I accidentally committed a change that broke the examples on the demo site. I've reverted that regression here ❤️
> reference CDN in examples

- README.md
- custom-elements.json
- src/auto-check-element.ts
- test/auto-check.js
This adds a method to the web component to manually trigger the auto-check element to validate the input.  This is useful for validating pre-populated fields on a form as the auto-check element does not currently validate fields if they have not been changed since load.  Using this method, we can force the auto-check element to validate the input as needed.
(For Hubbers) see internal issue: github/new-user-experience#292
> Add manual validation trigger

- custom-elements.json
- examples/index.html
- src/auto-check-element.ts
- test/auto-check.js
Us folks working on improving the GitHub.com signup flow are looking to address a UX/a11y concern with the `auto-check` element: it validates on _every_ keystroke.
- This UX is frustrating to users who may not have provided a _complete_ input yet, such as a partial email address in our case. 
- This UX is frustrating to screen reader users who are spammed with announcements on every keystroke.
We should modify the behavior to align with https://primer.style/ui-patterns/forms/overview#inline-validation, which states:
> Don't attempt to validate an input before the user is done with it. Validation may be performed as the user is typing or making their selection, but only after the first time the input has been validated and the input is in an invalid state. This gives the user early …
> [BREAKING] Align behavior with Primer guidance by default
